### ISSUE TITLE
0.12

### ISSUE THREAD

**Issue by insin** [insin/nwb#121]
- [x] #12 - Babel 6
- [x] #73  - implement deterministic hashing for long-term caching
- [x] #97 - remove `propTypes` from production build - depends on Babel6
- [x] #124 - add a `--preact` flag for React app builds using preact-compat
- [x] #125 - add `webpack.aliases` config
- [x] Update code coverage set up to use `nyc` (only for nwb itself) and `babel-plugin-istanbul`

---

...lots of other stuff happened in the meantime...

---

- [x] #145 - configure react-component builds to wrap `propTypes` with an env check
- [x] `nwb check-config` - allow errors & deprecations to be viewed outside of a build, and add tips where nwb has made it easier to do something (e.g. use `webpack.aliases` instead of `webpack.resolve.alias`)
- [x] #137 - add `"module"` config to package.json
- [x] #148 - write guide docs

**Comment by developit** [comment]
🎂
