### ISSUE TITLE
0.17

### ISSUE THREAD

**Issue by insin** [insin/nwb#310]
- [x] 21f57ba - use [https://github.com/webpack/webpack-dev-server](webpack-dev-server) instead of our own Express server and add `devServer` config to `nwb.config.js` - doing so adds `disableDotRule`, `https` and `proxy` (#69) support 
- [x] Add `--no-html` flag for people who will handle that themselves (#278)
- [ ] Provide full HMR URL to the client so HMR works when it's run from a different host/port (see #279 for use case)
