### ISSUE TITLE
0.8

### ISSUE THREAD

**Issue by insin** [insin/nwb#45]
Using issues for next release planning now, as Milestones are useless for tracking progress when working in the [`next` branch](https://github.com/insin/nwb/tree/next).

- [x] #65 merge `webpack.extra` into webpack config (replaces  #43 - support adding new Webpack plugins via user config)
- [x] #59 - replace npm-install-loader with npm-install-webpack-plugin
- [x] #56 - `nwb.config.js` should only be required for generic build commands which need `.type`
  - [x] Document
- [x] #44 - make config more consistent
- [x] #41 - always run tools in the user's working directory
  - [x] Update docs
- [x] #40 - move the current template project README.md contents to a CONTRIBUTING.md
