### ISSUE TITLE
0.9

### ISSUE THREAD

**Issue by insin** [insin/nwb#66]
- [x] f5b3ada43b6c3eb279657d9105dd04f408029718 - remove backwards-compat support for `nwb.config.js` format changes in 0.8 

Major theme for this release: changing how nwb builds apps - instead of building into `public/build/`, it will build into `dist/` and generate `index.html` - this gets rid of a weird discrepancy between development mode and builds, which caused (expected) 404s when using `serve`.

- [x] Move `index.html` from `public/` to `src/` and remove hardcoded CSS and JS resources
- [x] #34 - inject webpack assets instead of hardcoding them in `index.html`
- [x] #38 - use filenames for resources managed by file-loader and inclde a content hash for cachebusting
- [x] `public/` will now be copied to `dist/` as part of app builds
- [x] Fallback for HTML5 history will now have to proxy the request instead of sending an `index.html` file, as there won't be one in development mode.
- [x] #50 - add option to run server with custom IP
- [x] #63 - use Babel's `breakConfig` option to avoid in-scope `.babelrc` files breaking things
