### ISSUE TITLE
0.11

### ISSUE THREAD

**Issue by insin** [insin/nwb#84]
- [x] #57 - replace autoprefixer-loader (now deprecated) with postcss-loader in the default loader pipeline

---

Deferred:

- [ ] #97 - remove `propTypes` from production build - depends on Babel6
- [ ] #73  - use content hashes in generated JS and CSS file names for cachebusting - current status: working by coincidence in a branch
